FROM mcr.microsoft.com/powershell:latest

# this will copy the script from local to container in a folder called scripts. lets see how this works
COPY runme.ps1 /scripts/runme.ps1
COPY runme.py /scripts/runme.py 
COPY runme.sh /scripts/runme.sh

# lets add some support for python scripts as well.
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
