FROM mcr.microsoft.com/powershell:latest

COPY logging.psm1 modules/logging.psm1
# lets add some support for python scripts as well.
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
